<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'label' => 'beauty niche',
                'title' => 'Luxe Beauty Studio',
                'client_niche' => 'Beauty salon',
                'theme' => 'bronze',
                'layout' => 'phone-left',
                'image' => 'images/projects/devsuite-crm.svg',
                'row' => 1,
                'sort_order' => 1,
                'is_featured' => true,
                'description' => 'Instagram packaging, reels ritmi va lead form orqali bron qilish oqimi qayta yig\'ildi.',
                'before_state' => 'Profil chiroyli, lekin offer va kontent yo\'nalishi tarqoq edi.',
                'work_done' => 'Bio, highlights, reels hooklari, kontent plan va target testlari tuzildi.',
                'result' => '+43% reach',
                'platform' => 'Instagram',
            ],
            [
                'label' => 'education',
                'title' => 'EduPro Academy',
                'client_niche' => 'Online kurs',
                'theme' => 'graphite',
                'layout' => 'centered',
                'image' => 'images/projects/codepilot-ai.svg',
                'row' => 1,
                'sort_order' => 2,
                'description' => 'Kurs sotuviga yo\'naltirilgan content funnel va stories scriptlar.',
                'before_state' => 'Kurs haqida ma\'lumot ko\'p, lekin sotuv yo\'li aniq emas edi.',
                'work_done' => 'Lead magnet, kontent rubrikalari va retarget reklama strukturasini berdik.',
                'result' => '120 ta lead',
                'platform' => 'Instagram / Telegram',
            ],
            [
                'label' => 'food brand',
                'title' => 'Urban Cafe',
                'client_niche' => 'Cafe',
                'theme' => 'obsidian',
                'layout' => 'wide',
                'image' => 'images/projects/deployboard.svg',
                'row' => 1,
                'sort_order' => 3,
                'description' => 'Reels va TikTok orqali yangi menyu launch kampaniyasi.',
                'before_state' => 'Kontent faqat mahsulot rasmidan iborat edi.',
                'work_done' => 'Video hooklar, UGC formatlar va weekly content plan ishlab chiqildi.',
                'result' => '2.4x sales',
                'platform' => 'TikTok / Instagram',
            ],
            [
                'label' => 'fashion',
                'title' => 'Moda Line',
                'client_niche' => 'Fashion boutique',
                'theme' => 'champagne',
                'layout' => 'phone-left',
                'image' => 'images/projects/nimbus-saas.svg',
                'row' => 1,
                'sort_order' => 4,
                'description' => 'Vizual grid va influencer-style reels konsepti.',
                'before_state' => 'Sahifa premium mahsulotga mos signal bermas edi.',
                'work_done' => 'Moodboard, rubrikalar, stories paket va launch kreativlari.',
                'result' => '+68% profile visits',
                'platform' => 'Instagram',
            ],
            [
                'label' => 'service business',
                'title' => 'CleanPro Service',
                'client_niche' => 'Cleaning service',
                'theme' => 'blush',
                'layout' => 'centered',
                'image' => 'images/projects/stackforge.svg',
                'row' => 1,
                'sort_order' => 5,
                'description' => 'Xizmat biznesi uchun trust kontent va lead generation.',
                'before_state' => 'Mijozlarda ishonch uyg\'otadigan proof yetishmas edi.',
                'work_done' => 'Before/after kontent, offer, lead form va target segmentlar.',
                'result' => '87 ta so\'rov',
                'platform' => 'Instagram',
            ],
            [
                'label' => 'clinic',
                'title' => 'Smile Clinic',
                'client_niche' => 'Dental clinic',
                'theme' => 'amber',
                'layout' => 'wide',
                'image' => 'images/projects/fintrack-pro.svg',
                'row' => 2,
                'sort_order' => 1,
                'description' => 'Ekspert kontent, vrach personal brand va appointment funnel.',
                'before_state' => 'Kontent klinika xizmatlarini oddiy ro\'yxat qilib ko\'rsatar edi.',
                'work_done' => 'Ekspert reels, savol-javob, case proof va reklama funnel.',
                'result' => '+31% bookings',
                'platform' => 'Instagram / Telegram',
            ],
            [
                'label' => 'real estate',
                'title' => 'Prime Estate',
                'client_niche' => 'Real estate',
                'theme' => 'violet',
                'layout' => 'phone-left',
                'image' => 'images/projects/voxel-admin.svg',
                'row' => 2,
                'sort_order' => 2,
                'description' => 'Obyektlarni video formatda sotuvchi kontent tizimi.',
                'before_state' => 'Postlar informativ, lekin qiziqtiruvchi hook yo\'q edi.',
                'work_done' => 'Short-video script, lead CTA va auditoriya segmentlari.',
                'result' => '54 ta lead',
                'platform' => 'Instagram / TikTok',
            ],
            [
                'label' => 'fitness',
                'title' => 'FitZone Club',
                'client_niche' => 'Fitness club',
                'theme' => 'graphite',
                'layout' => 'centered',
                'image' => 'images/projects/cloudops-hub.svg',
                'row' => 2,
                'sort_order' => 3,
                'description' => 'Community, transformation kontent va membership offer.',
                'before_state' => 'Kontent faqat zal kadrlari bilan cheklangan edi.',
                'work_done' => 'Transformation stories, reels plan va promo campaign.',
                'result' => '+2.1x trial requests',
                'platform' => 'Instagram',
            ],
            [
                'label' => 'personal brand',
                'title' => 'Expert Coach',
                'client_niche' => 'Personal brand',
                'theme' => 'obsidian',
                'layout' => 'phone-left',
                'image' => 'images/projects/neurodash.svg',
                'row' => 2,
                'sort_order' => 4,
                'description' => 'Ekspert kontent, kursga olib kiruvchi storytelling va trust flow.',
                'before_state' => 'Ekspert kuchli, lekin sahifada positioning noaniq edi.',
                'work_done' => 'Content pillars, bio, reels hook va webinar funnel.',
                'result' => '3.6x saves',
                'platform' => 'Instagram / Telegram',
            ],
            [
                'label' => 'e-commerce',
                'title' => 'Mini Market',
                'client_niche' => 'Online shop',
                'theme' => 'champagne',
                'layout' => 'wide',
                'image' => 'images/projects/taskflow-erp.svg',
                'row' => 2,
                'sort_order' => 5,
                'description' => 'Mahsulot kontenti, offer va reklama testlari orqali sotuvni oshirish.',
                'before_state' => 'Mahsulot ko\'p, lekin offer va kategoriyalar tartibsiz edi.',
                'work_done' => 'Catalog content, offer set, creatives va retarget setup.',
                'result' => '+39% orders',
                'platform' => 'Instagram / Telegram',
            ],
        ];

        foreach ($projects as $project) {
            Project::query()->updateOrCreate(
                ['slug' => Str::slug($project['title'])],
                $project + [
                    'is_active' => true,
                ],
            );
        }
    }
}
